### ISSUE TITLE
NoSuchProviderException

### ISSUE THREAD

**Issue by joaovictortinoco** [moip/moip-sdk-android#8]
Hello!
I've followed the guidelines of the MOIP integration but during the encryption process i got this log:

> java.security.NoSuchProviderException: No such provider: SC
> 08-27 02:01:10.610 4430-4430/com.br.pckshop W/System.err:     at javax.crypto.Cipher.getInstance(Cipher.java:855)
> 08-27 02:01:10.610 4430-4430/com.br.pckshop W/System.err:     at br.com.moip.encryption.entities.CreditCard.encrypt(CreditCard.java:111)

**Comment by gmribas** [comment]
The same for me.

**Comment by micaelomota** [comment]
I'm also getting this problem. 
I've tried to use @joaovictortinoco sugestion, but what is BouncyCastleProvider()?

**Comment by PrinceBE** [comment]
I am also getting this Problem
Added this line
Security.addProvider(BouncyCastleProvider())
 Still problem didn't resolved please help us.

**Comment by caueferreira** [comment]
@PrinceBE 
`Security.addProvider(new BouncyCastleProvider());` should do the trick. Are you getting the same exception?

@micaelomota  
BouncyCastleProvider() is an instance of the bouncy castle library that allows the `encryptor` to proper cryptography the credit card data.

**Comment by PrinceBE** [comment]
Yes i am getting same exception

**Comment by PrinceBE** [comment]
Any one here to help? @caueferreira

**Comment by PrinceBE** [comment]
Its been a week and since no reply from your side. A bad support from your team.

**Comment by caueferreira** [comment]
I've just created a simple application. @PrinceBE did you added the `BouncyCastleProvider()` within the same activity you call `encrypt()` method?

**Comment by PrinceBE** [comment]
Yes I added  below snippet to encrypt the card
CreditCard creditCard = new CreditCard();
                    creditCard.setCvc(cvc.getText().toString());
                    creditCard.setNumber(cardNumber.getText().toString());
                    creditCard.setExpirationMonth(String.valueOf(month));
                    creditCard.setExpirationYear(String.valueOf(year));
                    creditCard.setPublicKey(MOIP_PUBLIC_KEY);
                    try {
                        String encryptedKey = creditCard.encrypt();
                    } catch (MoipEncryptionException e) {
                        e.printStackTrace();
                    }


Added this line in activity's Oncreate:
Security.addProvider(new BouncyCastleProvider());

**Comment by caueferreira** [comment]
That's weird... Which android sdk version are you compiling? I can't recreate this error.

**Comment by PrinceBE** [comment]
Any update from you side??

**Comment by caueferreira** [comment]
I've just added a working app. Could you see if it works for you? If so, I'll merge it afterwards.
https://github.com/moip/moip-encryption-sdk-android/tree/add-simple-app
